### ISSUE TITLE
User tagging not working

### ISSUE THREAD

**Issue by sultanboss** [Xon/XenForo-UserTaggingImprovements#7]
Installed the plugin, set up permission but for some reason user tagging not showing user list when '@' sing triggered. Same problem for user groups. No list, please help!

**Comment by Xon** [comment]
I will only provide such add-on support on https://xenforo.com/community/threads/user-mentions-improvements-by-xon.101527/ which requires a valid XenForo Licence.

Github issues are for technical issues and PRs
